<?php

use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')
            ->insert(
                array(

                    array("name_english" => "Afghanistan", "code_alpha2" => "AF", "code_alpha3" => "AFG", "code_number" => 4, "currency_code" => ""),
                    array("name_english" => "Aland Islands", "code_alpha2" => "AX", "code_alpha3" => "ALA", "code_number" => 248, "currency_code" => ""),
                    array("name_english" => "Albania", "code_alpha2" => "AL", "code_alpha3" => "ALB", "code_number" => 8, "currency_code" => ""),
                    array("name_english" => "Algeria", "code_alpha2" => "DZ", "code_alpha3" => "DZA", "code_number" => 12, "currency_code" => ""),
                    array("name_english" => "American Samoa", "code_alpha2" => "AS", "code_alpha3" => "ASM", "code_number" => 16, "currency_code" => ""),
                    array("name_english" => "Andorra", "code_alpha2" => "AD", "code_alpha3" => "AND", "code_number" => 20, "currency_code" => ""),
                    array("name_english" => "Angola", "code_alpha2" => "AO", "code_alpha3" => "AGO", "code_number" => 24, "currency_code" => ""),
                    array("name_english" => "Anguilla", "code_alpha2" => "AI", "code_alpha3" => "AIA", "code_number" => 660, "currency_code" => ""),
                    array("name_english" => "Antarctica", "code_alpha2" => "AQ", "code_alpha3" => "ATA", "code_number" => 10, "currency_code" => ""),
                    array("name_english" => "Antigua and Barbuda", "code_alpha2" => "AG", "code_alpha3" => "ATG", "code_number" => 28, "currency_code" => ""),
                    array("name_english" => "Argentina", "code_alpha2" => "AR", "code_alpha3" => "ARG", "code_number" => 32, "currency_code" => "ARS"),
                    array("name_english" => "Armenia", "code_alpha2" => "AM", "code_alpha3" => "ARM", "code_number" => 51, "currency_code" => ""),
                    array("name_english" => "Aruba", "code_alpha2" => "AW", "code_alpha3" => "ABW", "code_number" => 533, "currency_code" => ""),
                    array("name_english" => "Australia", "code_alpha2" => "AU", "code_alpha3" => "AUS", "code_number" => 36, "currency_code" => ""),
                    array("name_english" => "Austria", "code_alpha2" => "AT", "code_alpha3" => "AUT", "code_number" => 40, "currency_code" => ""),
                    array("name_english" => "Azerbaijan", "code_alpha2" => "AZ", "code_alpha3" => "AZE", "code_number" => 31, "currency_code" => ""),
                    array("name_english" => "Bahamas", "code_alpha2" => "BS", "code_alpha3" => "BHS", "code_number" => 44, "currency_code" => ""),
                    array("name_english" => "Bahrain", "code_alpha2" => "BH", "code_alpha3" => "BHR", "code_number" => 48, "currency_code" => ""),
                    array("name_english" => "Bangladesh", "code_alpha2" => "BD", "code_alpha3" => "BGD", "code_number" => 50, "currency_code" => ""),
                    array("name_english" => "Barbados", "code_alpha2" => "BB", "code_alpha3" => "BRB", "code_number" => 52, "currency_code" => ""),
                    array("name_english" => "Belarus", "code_alpha2" => "BY", "code_alpha3" => "BLR", "code_number" => 112, "currency_code" => ""),
                    array("name_english" => "Belgium", "code_alpha2" => "BE", "code_alpha3" => "BEL", "code_number" => 56, "currency_code" => ""),
                    array("name_english" => "Belize", "code_alpha2" => "BZ", "code_alpha3" => "BLZ", "code_number" => 84, "currency_code" => ""),
                    array("name_english" => "Benin", "code_alpha2" => "BJ", "code_alpha3" => "BEN", "code_number" => 204, "currency_code" => ""),
                    array("name_english" => "Bermuda", "code_alpha2" => "BM", "code_alpha3" => "BMU", "code_number" => 60, "currency_code" => ""),
                    array("name_english" => "Bhutan", "code_alpha2" => "BT", "code_alpha3" => "BTN", "code_number" => 64, "currency_code" => ""),
                    array("name_english" => "Bolivia", "code_alpha2" => "BO", "code_alpha3" => "BOL", "code_number" => 68, "currency_code" => ""),
                    array("name_english" => "Bosnia and Herzegovina", "code_alpha2" => "BA", "code_alpha3" => "BIH", "code_number" => 70, "currency_code" => ""),
                    array("name_english" => "Botswana", "code_alpha2" => "BW", "code_alpha3" => "BWA", "code_number" => 72, "currency_code" => ""),
                    array("name_english" => "Bouvet Island", "code_alpha2" => "BV", "code_alpha3" => "BVT", "code_number" => 74, "currency_code" => ""),
                    array("name_english" => "Brazil", "code_alpha2" => "BR", "code_alpha3" => "BRA", "code_number" => 76, "currency_code" => ""),
                    array("name_english" => "British Virgin Islands", "code_alpha2" => "VG", "code_alpha3" => "VGB", "code_number" => 92, "currency_code" => ""),
                    array("name_english" => "British Indian Ocean Territory", "code_alpha2" => "IO", "code_alpha3" => "IOT", "code_number" => 86, "currency_code" => ""),
                    array("name_english" => "Brunei Darussalam", "code_alpha2" => "BN", "code_alpha3" => "BRN", "code_number" => 96, "currency_code" => ""),
                    array("name_english" => "Bulgaria", "code_alpha2" => "BG", "code_alpha3" => "BGR", "code_number" => 100, "currency_code" => ""),
                    array("name_english" => "Burkina Faso", "code_alpha2" => "BF", "code_alpha3" => "BFA", "code_number" => 854, "currency_code" => ""),
                    array("name_english" => "Burundi", "code_alpha2" => "BI", "code_alpha3" => "BDI", "code_number" => 108, "currency_code" => ""),
                    array("name_english" => "Cambodia", "code_alpha2" => "KH", "code_alpha3" => "KHM", "code_number" => 116, "currency_code" => ""),
                    array("name_english" => "Cameroon", "code_alpha2" => "CM", "code_alpha3" => "CMR", "code_number" => 120, "currency_code" => ""),
                    array("name_english" => "Canada", "code_alpha2" => "CA", "code_alpha3" => "CAN", "code_number" => 124, "currency_code" => ""),
                    array("name_english" => "Cape Verde", "code_alpha2" => "CV", "code_alpha3" => "CPV", "code_number" => 132, "currency_code" => ""),
                    array("name_english" => "Cayman Islands ", "code_alpha2" => "KY", "code_alpha3" => "CYM", "code_number" => 136, "currency_code" => ""),
                    array("name_english" => "Central African Republic", "code_alpha2" => "CF", "code_alpha3" => "CAF", "code_number" => 140, "currency_code" => ""),
                    array("name_english" => "Chad", "code_alpha2" => "TD", "code_alpha3" => "TCD", "code_number" => 148, "currency_code" => ""),
                    array("name_english" => "Chile", "code_alpha2" => "CL", "code_alpha3" => "CHL", "code_number" => 152, "currency_code" => ""),
                    array("name_english" => "China", "code_alpha2" => "CN", "code_alpha3" => "CHN", "code_number" => 156, "currency_code" => ""),
                    array("name_english" => "Hong Kong, SAR China", "code_alpha2" => "HK", "code_alpha3" => "HKG", "code_number" => 344, "currency_code" => ""),
                    array("name_english" => "Macao, SAR China", "code_alpha2" => "MO", "code_alpha3" => "MAC", "code_number" => 446, "currency_code" => ""),
                    array("name_english" => "Christmas Island", "code_alpha2" => "CX", "code_alpha3" => "CXR", "code_number" => 162, "currency_code" => ""),
                    array("name_english" => "Cocos (Keeling) Islands", "code_alpha2" => "CC", "code_alpha3" => "CCK", "code_number" => 166, "currency_code" => ""),
                    array("name_english" => "Colombia", "code_alpha2" => "CO", "code_alpha3" => "COL", "code_number" => 170, "currency_code" => ""),
                    array("name_english" => "Comoros", "code_alpha2" => "KM", "code_alpha3" => "COM", "code_number" => 174, "currency_code" => ""),
                    array("name_english" => "Congo (Brazzaville)", "code_alpha2" => "CG", "code_alpha3" => "COG", "code_number" => 178, "currency_code" => ""),
                    array("name_english" => "Congo, (Kinshasa)", "code_alpha2" => "CD", "code_alpha3" => "COD", "code_number" => 180, "currency_code" => ""),
                    array("name_english" => "Cook Islands ", "code_alpha2" => "CK", "code_alpha3" => "COK", "code_number" => 184, "currency_code" => ""),
                    array("name_english" => "Costa Rica", "code_alpha2" => "CR", "code_alpha3" => "CRI", "code_number" => 188, "currency_code" => ""),
                    array("name_english" => "Côte d'Ivoire", "code_alpha2" => "CI", "code_alpha3" => "CIV", "code_number" => 384, "currency_code" => ""),
                    array("name_english" => "Croatia", "code_alpha2" => "HR", "code_alpha3" => "HRV", "code_number" => 191, "currency_code" => ""),
                    array("name_english" => "Cuba", "code_alpha2" => "CU", "code_alpha3" => "CUB", "code_number" => 192, "currency_code" => ""),
                    array("name_english" => "Cyprus", "code_alpha2" => "CY", "code_alpha3" => "CYP", "code_number" => 196, "currency_code" => ""),
                    array("name_english" => "Czech Republic", "code_alpha2" => "CZ", "code_alpha3" => "CZE", "code_number" => 203, "currency_code" => ""),
                    array("name_english" => "Denmark", "code_alpha2" => "DK", "code_alpha3" => "DNK", "code_number" => 208, "currency_code" => ""),
                    array("name_english" => "Djibouti", "code_alpha2" => "DJ", "code_alpha3" => "DJI", "code_number" => 262, "currency_code" => ""),
                    array("name_english" => "Dominica", "code_alpha2" => "DM", "code_alpha3" => "DMA", "code_number" => 212, "currency_code" => ""),
                    array("name_english" => "Dominican Republic", "code_alpha2" => "DO", "code_alpha3" => "DOM", "code_number" => 214, "currency_code" => ""),
                    array("name_english" => "Ecuador", "code_alpha2" => "EC", "code_alpha3" => "ECU", "code_number" => 218, "currency_code" => ""),
                    array("name_english" => "Egypt", "code_alpha2" => "EG", "code_alpha3" => "EGY", "code_number" => 818, "currency_code" => ""),
                    array("name_english" => "El Salvador", "code_alpha2" => "SV", "code_alpha3" => "SLV", "code_number" => 222, "currency_code" => ""),
                    array("name_english" => "Equatorial Guinea", "code_alpha2" => "GQ", "code_alpha3" => "GNQ", "code_number" => 226, "currency_code" => ""),
                    array("name_english" => "Eritrea", "code_alpha2" => "ER", "code_alpha3" => "ERI", "code_number" => 232, "currency_code" => ""),
                    array("name_english" => "Estonia", "code_alpha2" => "EE", "code_alpha3" => "EST", "code_number" => 233, "currency_code" => ""),
                    array("name_english" => "Ethiopia", "code_alpha2" => "ET", "code_alpha3" => "ETH", "code_number" => 231, "currency_code" => ""),
                    array("name_english" => "Falkland Islands (Malvinas)", "code_alpha2" => "FK", "code_alpha3" => "FLK", "code_number" => 238, "currency_code" => ""),
                    array("name_english" => "Faroe Islands", "code_alpha2" => "FO", "code_alpha3" => "FRO", "code_number" => 234, "currency_code" => ""),
                    array("name_english" => "Fiji", "code_alpha2" => "FJ", "code_alpha3" => "FJI", "code_number" => 242, "currency_code" => ""),
                    array("name_english" => "Finland", "code_alpha2" => "FI", "code_alpha3" => "FIN", "code_number" => 246, "currency_code" => ""),
                    array("name_english" => "France", "code_alpha2" => "FR", "code_alpha3" => "FRA", "code_number" => 250, "currency_code" => ""),
                    array("name_english" => "French Guiana", "code_alpha2" => "GF", "code_alpha3" => "GUF", "code_number" => 254, "currency_code" => ""),
                    array("name_english" => "French Polynesia", "code_alpha2" => "PF", "code_alpha3" => "PYF", "code_number" => 258, "currency_code" => ""),
                    array("name_english" => "French Southern Territories", "code_alpha2" => "TF", "code_alpha3" => "ATF", "code_number" => 260, "currency_code" => ""),
                    array("name_english" => "Gabon", "code_alpha2" => "GA", "code_alpha3" => "GAB", "code_number" => 266, "currency_code" => ""),
                    array("name_english" => "Gambia", "code_alpha2" => "GM", "code_alpha3" => "GMB", "code_number" => 270, "currency_code" => ""),
                    array("name_english" => "Georgia", "code_alpha2" => "GE", "code_alpha3" => "GEO", "code_number" => 268, "currency_code" => ""),
                    array("name_english" => "Germany", "code_alpha2" => "DE", "code_alpha3" => "DEU", "code_number" => 276, "currency_code" => ""),
                    array("name_english" => "Ghana", "code_alpha2" => "GH", "code_alpha3" => "GHA", "code_number" => 288, "currency_code" => ""),
                    array("name_english" => "Gibraltar ", "code_alpha2" => "GI", "code_alpha3" => "GIB", "code_number" => 292, "currency_code" => ""),
                    array("name_english" => "Greece", "code_alpha2" => "GR", "code_alpha3" => "GRC", "code_number" => 300, "currency_code" => ""),
                    array("name_english" => "Greenland", "code_alpha2" => "GL", "code_alpha3" => "GRL", "code_number" => 304, "currency_code" => ""),
                    array("name_english" => "Grenada", "code_alpha2" => "GD", "code_alpha3" => "GRD", "code_number" => 308, "currency_code" => ""),
                    array("name_english" => "Guadeloupe", "code_alpha2" => "GP", "code_alpha3" => "GLP", "code_number" => 312, "currency_code" => ""),
                    array("name_english" => "Guam", "code_alpha2" => "GU", "code_alpha3" => "GUM", "code_number" => 316, "currency_code" => ""),
                    array("name_english" => "Guatemala", "code_alpha2" => "GT", "code_alpha3" => "GTM", "code_number" => 320, "currency_code" => ""),
                    array("name_english" => "Guernsey", "code_alpha2" => "GG", "code_alpha3" => "GGY", "code_number" => 831, "currency_code" => ""),
                    array("name_english" => "Guinea", "code_alpha2" => "GN", "code_alpha3" => "GIN", "code_number" => 324, "currency_code" => ""),
                    array("name_english" => "Guinea-Bissau", "code_alpha2" => "GW", "code_alpha3" => "GNB", "code_number" => 624, "currency_code" => ""),
                    array("name_english" => "Guyana", "code_alpha2" => "GY", "code_alpha3" => "GUY", "code_number" => 328, "currency_code" => ""),
                    array("name_english" => "Haiti", "code_alpha2" => "HT", "code_alpha3" => "HTI", "code_number" => 332, "currency_code" => ""),
                    array("name_english" => "Heard and Mcdonald Islands", "code_alpha2" => "HM", "code_alpha3" => "HMD", "code_number" => 334, "currency_code" => ""),
                    array("name_english" => "Holy See (Vatican City State)", "code_alpha2" => "VA", "code_alpha3" => "VAT", "code_number" => 336, "currency_code" => ""),
                    array("name_english" => "Honduras", "code_alpha2" => "HN", "code_alpha3" => "HND", "code_number" => 340, "currency_code" => ""),
                    array("name_english" => "Hungary", "code_alpha2" => "HU", "code_alpha3" => "HUN", "code_number" => 348, "currency_code" => ""),
                    array("name_english" => "Iceland", "code_alpha2" => "IS", "code_alpha3" => "ISL", "code_number" => 352, "currency_code" => ""),
                    array("name_english" => "India", "code_alpha2" => "IN", "code_alpha3" => "IND", "code_number" => 356, "currency_code" => ""),
                    array("name_english" => "Indonesia", "code_alpha2" => "ID", "code_alpha3" => "IDN", "code_number" => 360, "currency_code" => ""),
                    array("name_english" => "Iran, Islamic Republic of", "code_alpha2" => "IR", "code_alpha3" => "IRN", "code_number" => 364, "currency_code" => ""),
                    array("name_english" => "Iraq", "code_alpha2" => "IQ", "code_alpha3" => "IRQ", "code_number" => 368, "currency_code" => ""),
                    array("name_english" => "Ireland", "code_alpha2" => "IE", "code_alpha3" => "IRL", "code_number" => 372, "currency_code" => ""),
                    array("name_english" => "Isle of Man ", "code_alpha2" => "IM", "code_alpha3" => "IMN", "code_number" => 833, "currency_code" => ""),
                    array("name_english" => "Israel", "code_alpha2" => "IL", "code_alpha3" => "ISR", "code_number" => 376, "currency_code" => ""),
                    array("name_english" => "Italy", "code_alpha2" => "IT", "code_alpha3" => "ITA", "code_number" => 380, "currency_code" => ""),
                    array("name_english" => "Jamaica", "code_alpha2" => "JM", "code_alpha3" => "JAM", "code_number" => 388, "currency_code" => ""),
                    array("name_english" => "Japan", "code_alpha2" => "JP", "code_alpha3" => "JPN", "code_number" => 392, "currency_code" => ""),
                    array("name_english" => "Jersey", "code_alpha2" => "JE", "code_alpha3" => "JEY", "code_number" => 832, "currency_code" => ""),
                    array("name_english" => "Jordan", "code_alpha2" => "JO", "code_alpha3" => "JOR", "code_number" => 400, "currency_code" => ""),
                    array("name_english" => "Kazakhstan", "code_alpha2" => "KZ", "code_alpha3" => "KAZ", "code_number" => 398, "currency_code" => ""),
                    array("name_english" => "Kenya", "code_alpha2" => "KE", "code_alpha3" => "KEN", "code_number" => 404, "currency_code" => ""),
                    array("name_english" => "Kiribati", "code_alpha2" => "KI", "code_alpha3" => "KIR", "code_number" => 296, "currency_code" => ""),
                    array("name_english" => "North Korea", "code_alpha2" => "KP", "code_alpha3" => "PRK", "code_number" => 408, "currency_code" => ""),
                    array("name_english" => "South Korea", "code_alpha2" => "KR", "code_alpha3" => "KOR", "code_number" => 410, "currency_code" => ""),
                    array("name_english" => "Kuwait", "code_alpha2" => "KW", "code_alpha3" => "KWT", "code_number" => 414, "currency_code" => ""),
                    array("name_english" => "Kyrgyzstan", "code_alpha2" => "KG", "code_alpha3" => "KGZ", "code_number" => 417, "currency_code" => ""),
                    array("name_english" => "Lao PDR", "code_alpha2" => "LA", "code_alpha3" => "LAO", "code_number" => 418, "currency_code" => ""),
                    array("name_english" => "Latvia", "code_alpha2" => "LV", "code_alpha3" => "LVA", "code_number" => 428, "currency_code" => ""),
                    array("name_english" => "Lebanon", "code_alpha2" => "LB", "code_alpha3" => "LBN", "code_number" => 422, "currency_code" => ""),
                    array("name_english" => "Lesotho", "code_alpha2" => "LS", "code_alpha3" => "LSO", "code_number" => 426, "currency_code" => ""),
                    array("name_english" => "Liberia", "code_alpha2" => "LR", "code_alpha3" => "LBR", "code_number" => 430, "currency_code" => ""),
                    array("name_english" => "Libya", "code_alpha2" => "LY", "code_alpha3" => "LBY", "code_number" => 434, "currency_code" => ""),
                    array("name_english" => "Liechtenstein", "code_alpha2" => "LI", "code_alpha3" => "LIE", "code_number" => 438, "currency_code" => ""),
                    array("name_english" => "Lithuania", "code_alpha2" => "LT", "code_alpha3" => "LTU", "code_number" => 440, "currency_code" => ""),
                    array("name_english" => "Luxembourg", "code_alpha2" => "LU", "code_alpha3" => "LUX", "code_number" => 442, "currency_code" => ""),
                    array("name_english" => "Macedonia, Republic of", "code_alpha2" => "MK", "code_alpha3" => "MKD", "code_number" => 807, "currency_code" => ""),
                    array("name_english" => "Madagascar", "code_alpha2" => "MG", "code_alpha3" => "MDG", "code_number" => 450, "currency_code" => ""),
                    array("name_english" => "Malawi", "code_alpha2" => "MW", "code_alpha3" => "MWI", "code_number" => 454, "currency_code" => ""),
                    array("name_english" => "Malaysia", "code_alpha2" => "MY", "code_alpha3" => "MYS", "code_number" => 458, "currency_code" => ""),
                    array("name_english" => "Maldives", "code_alpha2" => "MV", "code_alpha3" => "MDV", "code_number" => 462, "currency_code" => ""),
                    array("name_english" => "Mali", "code_alpha2" => "ML", "code_alpha3" => "MLI", "code_number" => 466, "currency_code" => ""),
                    array("name_english" => "Malta", "code_alpha2" => "MT", "code_alpha3" => "MLT", "code_number" => 470, "currency_code" => ""),
                    array("name_english" => "Marshall Islands", "code_alpha2" => "MH", "code_alpha3" => "MHL", "code_number" => 584, "currency_code" => ""),
                    array("name_english" => "Martinique", "code_alpha2" => "MQ", "code_alpha3" => "MTQ", "code_number" => 474, "currency_code" => ""),
                    array("name_english" => "Mauritania", "code_alpha2" => "MR", "code_alpha3" => "MRT", "code_number" => 478, "currency_code" => ""),
                    array("name_english" => "Mauritius", "code_alpha2" => "MU", "code_alpha3" => "MUS", "code_number" => 480, "currency_code" => ""),
                    array("name_english" => "Mayotte", "code_alpha2" => "YT", "code_alpha3" => "MYT", "code_number" => 175, "currency_code" => ""),
                    array("name_english" => "Mexico", "code_alpha2" => "MX", "code_alpha3" => "MEX", "code_number" => 484, "currency_code" => ""),
                    array("name_english" => "Micronesia, Federated States of", "code_alpha2" => "FM", "code_alpha3" => "FSM", "code_number" => 583, "currency_code" => ""),
                    array("name_english" => "Moldova", "code_alpha2" => "MD", "code_alpha3" => "MDA", "code_number" => 498, "currency_code" => ""),
                    array("name_english" => "Monaco", "code_alpha2" => "MC", "code_alpha3" => "MCO", "code_number" => 492, "currency_code" => ""),
                    array("name_english" => "Mongolia", "code_alpha2" => "MN", "code_alpha3" => "MNG", "code_number" => 496, "currency_code" => ""),
                    array("name_english" => "Montenegro", "code_alpha2" => "ME", "code_alpha3" => "MNE", "code_number" => 499, "currency_code" => ""),
                    array("name_english" => "Montserrat", "code_alpha2" => "MS", "code_alpha3" => "MSR", "code_number" => 500, "currency_code" => ""),
                    array("name_english" => "Morocco", "code_alpha2" => "MA", "code_alpha3" => "MAR", "code_number" => 504, "currency_code" => ""),
                    array("name_english" => "Mozambique", "code_alpha2" => "MZ", "code_alpha3" => "MOZ", "code_number" => 508, "currency_code" => ""),
                    array("name_english" => "Myanmar", "code_alpha2" => "MM", "code_alpha3" => "MMR", "code_number" => 104, "currency_code" => ""),
                    array("name_english" => "Namibia", "code_alpha2" => "NA", "code_alpha3" => "NAM", "code_number" => 516, "currency_code" => ""),
                    array("name_english" => "Nauru", "code_alpha2" => "NR", "code_alpha3" => "NRU", "code_number" => 520, "currency_code" => ""),
                    array("name_english" => "Nepal", "code_alpha2" => "NP", "code_alpha3" => "NPL", "code_number" => 524, "currency_code" => ""),
                    array("name_english" => "Netherlands", "code_alpha2" => "NL", "code_alpha3" => "NLD", "code_number" => 528, "currency_code" => ""),
                    array("name_english" => "Netherlands Antilles", "code_alpha2" => "AN", "code_alpha3" => "ANT", "code_number" => 530, "currency_code" => ""),
                    array("name_english" => "New Caledonia", "code_alpha2" => "NC", "code_alpha3" => "NCL", "code_number" => 540, "currency_code" => ""),
                    array("name_english" => "New Zealand", "code_alpha2" => "NZ", "code_alpha3" => "NZL", "code_number" => 554, "currency_code" => ""),
                    array("name_english" => "Nicaragua", "code_alpha2" => "NI", "code_alpha3" => "NIC", "code_number" => 558, "currency_code" => ""),
                    array("name_english" => "Niger", "code_alpha2" => "NE", "code_alpha3" => "NER", "code_number" => 562, "currency_code" => ""),
                    array("name_english" => "Nigeria", "code_alpha2" => "NG", "code_alpha3" => "NGA", "code_number" => 566, "currency_code" => ""),
                    array("name_english" => "Niue ", "code_alpha2" => "NU", "code_alpha3" => "NIU", "code_number" => 570, "currency_code" => ""),
                    array("name_english" => "Norfolk Island", "code_alpha2" => "NF", "code_alpha3" => "NFK", "code_number" => 574, "currency_code" => ""),
                    array("name_english" => "Northern Mariana Islands", "code_alpha2" => "MP", "code_alpha3" => "MNP", "code_number" => 580, "currency_code" => ""),
                    array("name_english" => "Norway", "code_alpha2" => "NO", "code_alpha3" => "NOR", "code_number" => 578, "currency_code" => ""),
                    array("name_english" => "Oman", "code_alpha2" => "OM", "code_alpha3" => "OMN", "code_number" => 512, "currency_code" => ""),
                    array("name_english" => "Pakistan", "code_alpha2" => "PK", "code_alpha3" => "PAK", "code_number" => 586, "currency_code" => ""),
                    array("name_english" => "Palau", "code_alpha2" => "PW", "code_alpha3" => "PLW", "code_number" => 585, "currency_code" => ""),
                    array("name_english" => "Palestinian Territory", "code_alpha2" => "PS", "code_alpha3" => "PSE", "code_number" => 275, "currency_code" => ""),
                    array("name_english" => "Panama", "code_alpha2" => "PA", "code_alpha3" => "PAN", "code_number" => 591, "currency_code" => ""),
                    array("name_english" => "Papua New Guinea", "code_alpha2" => "PG", "code_alpha3" => "PNG", "code_number" => 598, "currency_code" => ""),
                    array("name_english" => "Paraguay", "code_alpha2" => "PY", "code_alpha3" => "PRY", "code_number" => 600, "currency_code" => ""),
                    array("name_english" => "Peru", "code_alpha2" => "PE", "code_alpha3" => "PER", "code_number" => 604, "currency_code" => ""),
                    array("name_english" => "Philippines", "code_alpha2" => "PH", "code_alpha3" => "PHL", "code_number" => 608, "currency_code" => ""),
                    array("name_english" => "Pitcairn", "code_alpha2" => "PN", "code_alpha3" => "PCN", "code_number" => 612, "currency_code" => ""),
                    array("name_english" => "Poland", "code_alpha2" => "PL", "code_alpha3" => "POL", "code_number" => 616, "currency_code" => ""),
                    array("name_english" => "Portugal", "code_alpha2" => "PT", "code_alpha3" => "PRT", "code_number" => 620, "currency_code" => ""),
                    array("name_english" => "Puerto Rico", "code_alpha2" => "PR", "code_alpha3" => "PRI", "code_number" => 630, "currency_code" => ""),
                    array("name_english" => "Qatar", "code_alpha2" => "QA", "code_alpha3" => "QAT", "code_number" => 634, "currency_code" => ""),
                    array("name_english" => "Réunion", "code_alpha2" => "RE", "code_alpha3" => "REU", "code_number" => 638, "currency_code" => ""),
                    array("name_english" => "Romania", "code_alpha2" => "RO", "code_alpha3" => "ROU", "code_number" => 642, "currency_code" => ""),
                    array("name_english" => "Russian Federation", "code_alpha2" => "RU", "code_alpha3" => "RUS", "code_number" => 643, "currency_code" => ""),
                    array("name_english" => "Rwanda", "code_alpha2" => "RW", "code_alpha3" => "RWA", "code_number" => 646, "currency_code" => ""),
                    array("name_english" => "Saint-Barthélemy", "code_alpha2" => "BL", "code_alpha3" => "BLM", "code_number" => 652, "currency_code" => ""),
                    array("name_english" => "Saint Helena", "code_alpha2" => "SH", "code_alpha3" => "SHN", "code_number" => 654, "currency_code" => ""),
                    array("name_english" => "Saint Kitts and Nevis", "code_alpha2" => "KN", "code_alpha3" => "KNA", "code_number" => 659, "currency_code" => ""),
                    array("name_english" => "Saint Lucia", "code_alpha2" => "LC", "code_alpha3" => "LCA", "code_number" => 662, "currency_code" => ""),
                    array("name_english" => "Saint-Martin (French part)", "code_alpha2" => "MF", "code_alpha3" => "MAF", "code_number" => 663, "currency_code" => ""),
                    array("name_english" => "Saint Pierre and Miquelon ", "code_alpha2" => "PM", "code_alpha3" => "SPM", "code_number" => 666, "currency_code" => ""),
                    array("name_english" => "Saint Vincent and Grenadines", "code_alpha2" => "VC", "code_alpha3" => "VCT", "code_number" => 670, "currency_code" => ""),
                    array("name_english" => "Samoa", "code_alpha2" => "WS", "code_alpha3" => "WSM", "code_number" => 882, "currency_code" => ""),
                    array("name_english" => "San Marino", "code_alpha2" => "SM", "code_alpha3" => "SMR", "code_number" => 674, "currency_code" => ""),
                    array("name_english" => "Sao Tome and Principe", "code_alpha2" => "ST", "code_alpha3" => "STP", "code_number" => 678, "currency_code" => ""),
                    array("name_english" => "Saudi Arabia", "code_alpha2" => "SA", "code_alpha3" => "SAU", "code_number" => 682, "currency_code" => ""),
                    array("name_english" => "Senegal", "code_alpha2" => "SN", "code_alpha3" => "SEN", "code_number" => 686, "currency_code" => ""),
                    array("name_english" => "Serbia", "code_alpha2" => "RS", "code_alpha3" => "SRB", "code_number" => 688, "currency_code" => ""),
                    array("name_english" => "Seychelles", "code_alpha2" => "SC", "code_alpha3" => "SYC", "code_number" => 690, "currency_code" => ""),
                    array("name_english" => "Sierra Leone", "code_alpha2" => "SL", "code_alpha3" => "SLE", "code_number" => 694, "currency_code" => ""),
                    array("name_english" => "Singapore", "code_alpha2" => "SG", "code_alpha3" => "SGP", "code_number" => 702, "currency_code" => ""),
                    array("name_english" => "Slovakia", "code_alpha2" => "SK", "code_alpha3" => "SVK", "code_number" => 703, "currency_code" => ""),
                    array("name_english" => "Slovenia", "code_alpha2" => "SI", "code_alpha3" => "SVN", "code_number" => 705, "currency_code" => ""),
                    array("name_english" => "Solomon Islands", "code_alpha2" => "SB", "code_alpha3" => "SLB", "code_number" => 90, "currency_code" => ""),
                    array("name_english" => "Somalia", "code_alpha2" => "SO", "code_alpha3" => "SOM", "code_number" => 706, "currency_code" => ""),
                    array("name_english" => "South Africa", "code_alpha2" => "ZA", "code_alpha3" => "ZAF", "code_number" => 710, "currency_code" => ""),
                    array("name_english" => "South Georgia and the South Sandwich Islands", "code_alpha2" => "GS", "code_alpha3" => "SGS", "code_number" => 239, "currency_code" => ""),
                    array("name_english" => "South Sudan", "code_alpha2" => "SS", "code_alpha3" => "SSD", "code_number" => 728, "currency_code" => ""),
                    array("name_english" => "Spain", "code_alpha2" => "ES", "code_alpha3" => "ESP", "code_number" => 724, "currency_code" => ""),
                    array("name_english" => "Sri Lanka", "code_alpha2" => "LK", "code_alpha3" => "LKA", "code_number" => 144, "currency_code" => ""),
                    array("name_english" => "Sudan", "code_alpha2" => "SD", "code_alpha3" => "SDN", "code_number" => 736, "currency_code" => ""),
                    array("name_english" => "Suriname", "code_alpha2" => "SR", "code_alpha3" => "SUR", "code_number" => 740, "currency_code" => ""),
                    array("name_english" => "Svalbard and Jan Mayen Islands ", "code_alpha2" => "SJ", "code_alpha3" => "SJM", "code_number" => 744, "currency_code" => ""),
                    array("name_english" => "Swaziland", "code_alpha2" => "SZ", "code_alpha3" => "SWZ", "code_number" => 748, "currency_code" => ""),
                    array("name_english" => "Sweden", "code_alpha2" => "SE", "code_alpha3" => "SWE", "code_number" => 752, "currency_code" => ""),
                    array("name_english" => "Switzerland", "code_alpha2" => "CH", "code_alpha3" => "CHE", "code_number" => 756, "currency_code" => ""),
                    array("name_english" => "Syrian Arab Republic (Syria)", "code_alpha2" => "SY", "code_alpha3" => "SYR", "code_number" => 760, "currency_code" => ""),
                    array("name_english" => "Taiwan, Republic of China", "code_alpha2" => "TW", "code_alpha3" => "TWN", "code_number" => 158, "currency_code" => ""),
                    array("name_english" => "Tajikistan", "code_alpha2" => "TJ", "code_alpha3" => "TJK", "code_number" => 762, "currency_code" => ""),
                    array("name_english" => "Tanzania, United Republic of", "code_alpha2" => "TZ", "code_alpha3" => "TZA", "code_number" => 834, "currency_code" => ""),
                    array("name_english" => "Thailand", "code_alpha2" => "TH", "code_alpha3" => "THA", "code_number" => 764, "currency_code" => ""),
                    array("name_english" => "Timor-Leste", "code_alpha2" => "TL", "code_alpha3" => "TLS", "code_number" => 626, "currency_code" => ""),
                    array("name_english" => "Togo", "code_alpha2" => "TG", "code_alpha3" => "TGO", "code_number" => 768, "currency_code" => ""),
                    array("name_english" => "Tokelau ", "code_alpha2" => "TK", "code_alpha3" => "TKL", "code_number" => 772, "currency_code" => ""),
                    array("name_english" => "Tonga", "code_alpha2" => "TO", "code_alpha3" => "TON", "code_number" => 776, "currency_code" => ""),
                    array("name_english" => "Trinidad and Tobago", "code_alpha2" => "TT", "code_alpha3" => "TTO", "code_number" => 780, "currency_code" => ""),
                    array("name_english" => "Tunisia", "code_alpha2" => "TN", "code_alpha3" => "TUN", "code_number" => 788, "currency_code" => ""),
                    array("name_english" => "Turkey", "code_alpha2" => "TR", "code_alpha3" => "TUR", "code_number" => 792, "currency_code" => ""),
                    array("name_english" => "Turkmenistan", "code_alpha2" => "TM", "code_alpha3" => "TKM", "code_number" => 795, "currency_code" => ""),
                    array("name_english" => "Turks and Caicos Islands ", "code_alpha2" => "TC", "code_alpha3" => "TCA", "code_number" => 796, "currency_code" => ""),
                    array("name_english" => "Tuvalu", "code_alpha2" => "TV", "code_alpha3" => "TUV", "code_number" => 798, "currency_code" => ""),
                    array("name_english" => "Uganda", "code_alpha2" => "UG", "code_alpha3" => "UGA", "code_number" => 800, "currency_code" => ""),
                    array("name_english" => "Ukraine", "code_alpha2" => "UA", "code_alpha3" => "UKR", "code_number" => 804, "currency_code" => ""),
                    array("name_english" => "United Arab Emirates", "code_alpha2" => "AE", "code_alpha3" => "ARE", "code_number" => 784, "currency_code" => ""),
                    array("name_english" => "United Kingdom", "code_alpha2" => "GB", "code_alpha3" => "GBR", "code_number" => 826, "currency_code" => ""),
                    array("name_english" => "United States", "code_alpha2" => "US", "code_alpha3" => "USA", "code_number" => 840, "currency_code" => ""),
                    array("name_english" => "US Minor Outlying Islands", "code_alpha2" => "UM", "code_alpha3" => "UMI", "code_number" => 581, "currency_code" => ""),
                    array("name_english" => "Uruguay", "code_alpha2" => "UY", "code_alpha3" => "URY", "code_number" => 858, "currency_code" => ""),
                    array("name_english" => "Uzbekistan", "code_alpha2" => "UZ", "code_alpha3" => "UZB", "code_number" => 860, "currency_code" => ""),
                    array("name_english" => "Vanuatu", "code_alpha2" => "VU", "code_alpha3" => "VUT", "code_number" => 548, "currency_code" => ""),
                    array("name_english" => "Venezuela", "code_alpha2" => "VE", "code_alpha3" => "VEN", "code_number" => 862, "currency_code" => ""),
                    array("name_english" => "Viet Nam", "code_alpha2" => "VN", "code_alpha3" => "VNM", "code_number" => 704, "currency_code" => ""),
                    array("name_english" => "Virgin Islands, US", "code_alpha2" => "VI", "code_alpha3" => "VIR", "code_number" => 850, "currency_code" => ""),
                    array("name_english" => "Wallis and Futuna Islands ", "code_alpha2" => "WF", "code_alpha3" => "WLF", "code_number" => 876, "currency_code" => ""),
                    array("name_english" => "Western Sahara", "code_alpha2" => "EH", "code_alpha3" => "ESH", "code_number" => 732, "currency_code" => ""),
                    array("name_english" => "Yemen", "code_alpha2" => "YE", "code_alpha3" => "YEM", "code_number" => 887, "currency_code" => ""),
                    array("name_english" => "Zambia", "code_alpha2" => "ZM", "code_alpha3" => "ZMB", "code_number" => 894, "currency_code" => ""),
                    array("name_english" => "Zimbabwe", "code_alpha2" => "ZW", "code_alpha3" => "ZWE", "code_number" => 716, "currency_code" => "")


                )
            );

    }
}
