<?php

return [

	// paises soportados de aseguratuviaje, son menos que los almacenados en la DB.
	"countries_from" => [
		["id" => 4, "name" => "Afghanistan"], 
		["id" => 8, "name" => "Albania"], 
		["id" => 12, "name" => "Argelia"], 
		["id" => 20, "name" => "Andorra"], 
		["id" => 24, "name" => "Angola"], 
		["id" => 28, "name" => "Antigua and Barbuda"], 
		["id" => 31, "name" => "Azerbaijan"], 
		["id" => 32, "name" => "Argentina"], 
		["id" => 36, "name" => "Australia"], 
		["id" => 40, "name" => "Austria"], 
		["id" => 44, "name" => "Bahamas"], 
		["id" => 48, "name" => "Bahrain"], 
		["id" => 50, "name" => "Bangladesh"], 
		["id" => 51, "name" => "Armenia"], 
		["id" => 52, "name" => "Barbados"], 
		["id" => 56, "name" => "Belgium"], 
		["id" => 60, "name" => "Bermuda"], 
		["id" => 64, "name" => "Butan"], 
		["id" => 68, "name" => "Bolivia"], 
		["id" => 70, "name" => "Bosnia"], 
		["id" => 72, "name" => "Botswana"], 
		["id" => 76, "name" => "Brazil"], 
		["id" => 84, "name" => "Belize"], 
		["id" => 90, "name" => "Solomon Islands"], 
		["id" => 96, "name" => "Brunei Darussulam"], 
		["id" => 100, "name" => "Bulgaria"], 
		["id" => 104, "name" => "Myanmar (Burma)"], 
		["id" => 108, "name" => "Burundi"], 
		["id" => 112, "name" => "Belarus"], 
		["id" => 116, "name" => "Cambodia"], 
		["id" => 120, "name" => "Cameroon"], 
		["id" => 124, "name" => "Canada"], 
		["id" => 132, "name" => "Cape Verde"], 
		["id" => 136, "name" => "Cayman Islands"], 
		["id" => 140, "name" => "Central African Republic"], 
		["id" => 144, "name" => "Sri Lanka (Ceylon)"], 
		["id" => 148, "name" => "Chad"], 
		["id" => 152, "name" => "Chile"], 
		["id" => 156, "name" => "China"], 
		["id" => 158, "name" => "Taiwan"], 
		["id" => 170, "name" => "Colombia"], 
		["id" => 174, "name" => "Comoros"], 
		["id" => 178, "name" => "Congo"], 
		["id" => 180, "name" => "Democratic Republic of Congo"], 
		["id" => 188, "name" => "Costa Rica"], 
		["id" => 191, "name" => "Croatia"], 
		["id" => 192, "name" => "Cuba"], 
		["id" => 196, "name" => "Cyprus"], 
		["id" => 203, "name" => "Czech Republic"], 
		["id" => 204, "name" => "Benin"], 
		["id" => 208, "name" => "Denmark"], 
		["id" => 212, "name" => "Dominica"], 
		["id" => 214, "name" => "Dominican Republic"], 
		["id" => 218, "name" => "Ecuador"], 
		["id" => 222, "name" => "El Salvador"],  //
		["id" => 226, "name" => "Equatorial Guinea"], 
		["id" => 231, "name" => "Ethiopia"], 
		["id" => 232, "name" => "Eritrea"], 
		["id" => 233, "name" => "Estonia"], 
		["id" => 234, "name" => "Faroe Islands"], 
		["id" => 238, "name" => "Falkland Islands"],  //
		["id" => 242, "name" => "Fiji"], 
		["id" => 246, "name" => "Finland"], 
		["id" => 250, "name" => "France"], 
		["id" => 254, "name" => "French Guiana"], 
		["id" => 258, "name" => "French Polynesia"], 
		["id" => 262, "name" => "Djibouti"], 
		["id" => 266, "name" => "Gabon"], 
		["id" => 268, "name" => "Georgia"], 
		["id" => 270, "name" => "Gambia"], 
		["id" => 275, "name" => "Palestine"], 
		["id" => 276, "name" => "Germany"], 
		["id" => 288, "name" => "Ghana"], 
		["id" => 296, "name" => "Kiribati"], 
		["id" => 300, "name" => "Greece"], 
		["id" => 304, "name" => "Greenland"], 
		["id" => 308, "name" => "Granada"], 
		["id" => 312, "name" => "Guadalupe"], 
		["id" => 316, "name" => "Guam"], 
		["id" => 320, "name" => "Guatemala"], 
		["id" => 324, "name" => "Guinea"], 
		["id" => 328, "name" => "Guyana"], 
		["id" => 332, "name" => "Haiti"], 
		["id" => 336, "name" => "Holy See (Vatican)"], 
		["id" => 340, "name" => "Honduras"], 
		["id" => 344, "name" => "Hong Kong"], 
		["id" => 348, "name" => "Hungary"], 
		["id" => 352, "name" => "Iceland"], 
		["id" => 356, "name" => "India"], 
		["id" => 360, "name" => "Indonesia"], 
		["id" => 364, "name" => "Iran"], 
		["id" => 368, "name" => "Iraq"], 
		["id" => 372, "name" => "Ireland"], 
		["id" => 376, "name" => "Israel"], 
		["id" => 380, "name" => "Italy"], 
		["id" => 384, "name" => "Ivory Coast"], 
		["id" => 388, "name" => "Jamaica"], 
		["id" => 392, "name" => "Japan"], 
		["id" => 398, "name" => "Kazakhstan"], 
		["id" => 400, "name" => "Jordan"], 
		["id" => 404, "name" => "Kenya"], 
		["id" => 408, "name" => "North Korea"], 
		["id" => 410, "name" => "South Korea"], 
		["id" => 414, "name" => "Kuwait"], 
		["id" => 417, "name" => "Kyrgyzstan"], 
		["id" => 418, "name" => "Laos"], 
		["id" => 422, "name" => "Lebanon"], 
		["id" => 426, "name" => "Lesotho"], 
		["id" => 428, "name" => "Latvia"], 
		["id" => 430, "name" => "Liberia"], 
		["id" => 434, "name" => "Libya"], 
		["id" => 438, "name" => "Liechtenstein"], 
		["id" => 440, "name" => "Lithuania"], 
		["id" => 442, "name" => "Luxembourg"], 
		["id" => 446, "name" => "Macao"], 
		["id" => 450, "name" => "Madagascar"], 
		["id" => 454, "name" => "Malawi"], 
		["id" => 458, "name" => "Malaysia"], 
		["id" => 462, "name" => "Maldive Islands"], 
		["id" => 466, "name" => "Mali"], 
		["id" => 470, "name" => "Malt"], 
		["id" => 474, "name" => "Martinique"], 
		["id" => 478, "name" => "Mauritania"], 
		["id" => 480, "name" => "Mauricio"], 
		["id" => 484, "name" => "Mexico"], 
		["id" => 492, "name" => "Monaco"], 
		["id" => 496, "name" => "Mongolia"], 
		["id" => 498, "name" => "Moldova"], 
		["id" => 504, "name" => "Morocco"], 
		["id" => 508, "name" => "Mozambique"], 
		["id" => 512, "name" => "Oman"], 
		["id" => 516, "name" => "Namibia"], 
		["id" => 524, "name" => "Nepal"], 
		["id" => 528, "name" => "Netherlands"], 
		["id" => 530, "name" => "Netherlands Antilles"], 
		["id" => 533, "name" => "Aruba"], 
		["id" => 540, "name" => "New Caledonia"], 
		["id" => 548, "name" => "Vanuatu"], 
		["id" => 554, "name" => "New Zealand"], 
		["id" => 558, "name" => "Nicaragua"], 
		["id" => 562, "name" => "Niger"], 
		["id" => 566, "name" => "Nigeria"], 
		["id" => 578, "name" => "Norway"], 
		["id" => 581, "name" => "Virgin Islands (U.S.)"], 
		["id" => 583, "name" => "Micronesia"], 
		["id" => 584, "name" => "Marshall Islands"], 
		["id" => 586, "name" => "Pakistan"], 
		["id" => 591, "name" => "Panama"], 
		["id" => 598, "name" => "Papua New Guinea"], 
		["id" => 600, "name" => "Paraguay"], 
		["id" => 604, "name" => "Peru"], 
		["id" => 608, "name" => "Philippines"], 
		["id" => 616, "name" => "Poland"], 
		["id" => 620, "name" => "Portugal"], 
		["id" => 624, "name" => "Guinea-Bissau"], 
		["id" => 626, "name" => "East Timor"], 
		["id" => 630, "name" => "Puerto Rico"], 
		["id" => 634, "name" => "Qatar"], 
		["id" => 638, "name" => "Reunion"], 
		["id" => 642, "name" => "Romania"], 
		["id" => 643, "name" => "Russia"], 
		["id" => 646, "name" => "Rwanda"], 
		["id" => 659, "name" => "St. Kitts - Nevis"], 
		["id" => 662, "name" => "St. lucia"], 
		["id" => 670, "name" => "Saint Vincent and the Grenadines"], 
		["id" => 674, "name" => "San Marino"], 
		["id" => 678, "name" => "Santo Tome & Principe"], 
		["id" => 682, "name" => "Saudi Arabia"], 
		["id" => 686, "name" => "Senegal"], 
		["id" => 690, "name" => "Seychelles"], 
		["id" => 694, "name" => "Sierra Leone"], 
		["id" => 702, "name" => "Singapore"], 
		["id" => 703, "name" => "Slovak Republic"], 
		["id" => 704, "name" => "Vietnam"], 
		["id" => 705, "name" => "Slovenia"], 
		["id" => 706, "name" => "Somalia"], 
		["id" => 710, "name" => "South Africa"], 
		["id" => 716, "name" => "Zimbabwe"], 
		["id" => 724, "name" => "Spain"], 
		["id" => 732, "name" => "Sahara"], 
		["id" => 736, "name" => "Sudan"], 
		["id" => 740, "name" => "Surinam"], 
		["id" => 748, "name" => "Swaziland"], 
		["id" => 752, "name" => "Sweden"], 
		["id" => 756, "name" => "Switzerland"], 
		["id" => 760, "name" => "Syria"], 
		["id" => 762, "name" => "Tajikistan"], 
		["id" => 764, "name" => "Thailand"], 
		["id" => 768, "name" => "Togo"], 
		["id" => 776, "name" => "Tonga"], 
		["id" => 780, "name" => "Trinidad & Tobago"], 
		["id" => 784, "name" => "United Arab Emirates"], 
		["id" => 788, "name" => "Tunisia"], 
		["id" => 792, "name" => "Turkey"], 
		["id" => 795, "name" => "Turkmenistan"], 
		["id" => 800, "name" => "Uganda"], 
		["id" => 804, "name" => "Ukraine"], 
		["id" => 807, "name" => "Macedionia"],  //
		["id" => 818, "name" => "Egypt"], 
		["id" => 826, "name" => "United Kingdom"], 
		["id" => 831, "name" => "Guerney"], 
		["id" => 832, "name" => "Jersey"], 
		["id" => 834, "name" => "Tanzania"], 
		["id" => 840, "name" => "United States"], 
		["id" => 854, "name" => "Burkina Faso"], 
		["id" => 858, "name" => "Uruguay"], 
		["id" => 860, "name" => "Uzbekistan"], 
		["id" => 862, "name" => "Venezuela"], 
		["id" => 882, "name" => "Samoa"], 
		["id" => 887, "name" => "Yemen"], 
		["id" => 890, "name" => "Yugoslavia"], 
		["id" => 894, "name" => "Zambia"]
	],


	"regions_to" => [

		["id" => 1001, "name" => "Central America"],
		["id" => 1000, "name" => "North America"],
		["id" => 1002, "name" => "South America"],
		["id" => 1005, "name" => "Asia"],
		["id" => 1004, "name" => "Europe"],
		["id" => 1006, "name" => "All of the world"],
		["id" => 1009, "name" => "National Coverage"]
	]


];
		


